version: '3.8'
services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONTAINER_TIMEZONE=${CONTAINER_TIMEZONE}
      - TZ=${TZ}
      - MYSQL_USER=domjudge
      - MYSQL_DATABASE=domjudge
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    networks:
      - dj_net

  domserver:
    image: domjudge/domserver:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:80
    environment:
      - CONTAINER_TIMEZONE=${CONTAINER_TIMEZONE}
      - TZ=${TZ}
      - MYSQL_HOST=db
      - MYSQL_USER=domjudge
      - MYSQL_DATABASE=domjudge
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    networks:
      - dj_net

  judgehost:
    image: domjudge/judgehost:latest
    env_file:
      - .env
    depends_on:
      - domserver
    restart: unless-stopped
    environment:
      - DOMSERVER_URL=http://domserver:80
      - CONTAINER_TIMEZONE=${CONTAINER_TIMEZONE}
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=0MZAdqpaJXVJcK+6+EWrF3bE5I8ZLpPz
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - dj_net

networks:
  dj_net:
